language: objective-c

branches:
  except:
    - gh-pages

install:
  - gem install xcpretty

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="ReSwift"
    - UPDATE_DOCS="true"

matrix:
  include:
    - osx_image: xcode9
      env: SCHEME="macOS"  SDK="macosx10.13"          DESTINATION="arch=x86_64"                    SWIFT_VERSION="3.2"
    - osx_image: xcode9
      env: SCHEME="macOS"  SDK="macosx10.13"          DESTINATION="arch=x86_64"                    SWIFT_VERSION="4.0"
    - osx_image: xcode9
      env: SCHEME="iOS"    SDK="iphonesimulator11.0"  DESTINATION="OS=11.0,name=iPhone 8"          SWIFT_VERSION="4.0"
    - osx_image: xcode9
      env: SCHEME="tvOS"   SDK="appletvsimulator11.0"  DESTINATION="OS=11.0,name=Apple TV 1080p"   SWIFT_VERSION="4.0"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    -project "$FRAMEWORK_NAME.xcodeproj"
    -scheme "$FRAMEWORK_NAME-$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    SWIFT_VERSION=$SWIFT_VERSION
    test

after_success:
  - bash <(curl -s https://codecov.io/bash) -J ReSwift
  - test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    test $UPDATE_DOCS == "true" &&
    .scripts/update-gh-pages
