language: objective-c

branches:
  except:
    - gh-pages

install:
  - gem install xcpretty

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="ReSwift"
    - UPDATE_DOCS="true"

matrix:
  include:
    - osx_image: xcode8.2
      env: SCHEME="macOS"  SDK="macosx10.12"          DESTINATION="arch=x86_64"
    - osx_image: xcode8.2
      env: SCHEME="iOS"    SDK="iphonesimulator10.2"  DESTINATION="OS=10.1,name=iPhone 6S Plus"
    - osx_image: xcode8.2
      env: SCHEME="tvOS"   SDK="appletvsimulator10.1"  DESTINATION="OS=10.1,name=Apple TV 1080p"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    -project "$FRAMEWORK_NAME.xcodeproj"
    -scheme "$FRAMEWORK_NAME-$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    test

after_success:
  - bash <(curl -s https://codecov.io/bash) -J ReSwift
  - test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    test $UPDATE_DOCS == "true" &&
    .scripts/update-gh-pages

before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME

deploy:
  provider: releases
  api_key:
    secure: S5BWCiwX80EWjF5043d1EVPw59qpuVTI1ytPejEE9bFomVDj0kCYIqodlUmKRorutNr+t2UD5CwTyqs5qHaAuseAm0P6SrOp1GaP9m6Jb/surII4nMICx+TzFP8xdCwC+C74CUDuCLeyM++kxIZEwJOp/QF9iP3iaF54ed+4IlycVEGxJ4LQQRBaQ3X+u6L/bSCgL/HuRzs0W1QXYovbFzCvEQmYlSQi00x5BGHtk3Rj4zU320pmcE1Ne0dGsmITN0oA2qSborVFPo1CnjRGKAJD8TJZRmxmKygFOQpsD4px/IRswDJRle5cGjvZ+MLnvDBis5siTGOf3W1z/HxTomqCIeAGt4O5CfJP9NP9HjaV9ATFb2NSpZPNaVle4IhfSl2O7NuQyhh19UKz9xgZ9QknkddZBPQ4yEINHAEzqVDKHjCvZZH4pxjN6AcbaKPYBoL042FmS87HAmq32AcOVBM0eXhMUzucahYTw1+XS77ZkOrXdx2jXX1hyjZ7tooYYm3SHJxHJKufnv5/rfShTM70+4vVhLePYGt/FnduacPdNtIehit7v6Dj+xsTs5igWMx/0Bb6ccaRr2ZQGs0dq536x0zrQVrvkrW9HcOY1uohFqujLGjJ/i6U1aMBf+iPRDTHlVmqiYjVSRC1mhatGOVHv+UuA1dSPkK9F91Lxbs=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: ReSwift/ReSwift
    tags: true
